spring.application.name=matching_app

# --- MariaDB ?? ?? ---
spring.datasource.driver-class-name=org.mariadb.jdbc.Driver
spring.datasource.url=jdbc:mariadb://db.wisejia.com:3303/j25a08?useUnicode=true&characterEncoding=utf8
spring.datasource.username=j25a08
spring.datasource.password=j25a08

# --- JPA/Hibernate ?? --- : update / ??: validate ?? none
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MariaDBDialect